# Generated by Django 5.1.4 on 2024-12-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpedanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('ambient_temperature', models.FloatField()),
                ('re', models.CharField(max_length=100)),
                ('rct', models.CharField(max_length=100)),
                ('capacity', models.FloatField()),
            ],
        ),
    ]
